server:
  port: 8090

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: nhnacademy123!

  config:
    activate:
      on-profile: prod

  application:
    name: bookstore

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


  #    datasource:
  #      url: jdbc:mysql://133.186.241.167:3306/project_be8_plzbuybook_bookstore  # MySQL 데이터베이스 URL
  #      driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버 클래스
  #      username: project_be8_plzbuybook # MySQL 사용자명
  #      password: MOW6c#y4TVxi1P5b  # MySQL 비밀번호

  datasource:
    url: ${app.skm.database.url}
    username: ${app.skm.database.username}
    password: ${app.skm.database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # 애플리케이션 실행 시 DB 스키마 자동 업데이트
    show-sql: false  # 실행되는 SQL을 콘솔에 출력
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL용 Hibernate Dialect

app:
  skm:
    url: https://api-keymanager.nhncloudservice.com
    appKey: qTQNj7LyHhdAazH3
    keystoreFile: skm.p12
    password: 4444
    database:
      url: 1117490ed9294c8798e83f2cb162982d
      username: 7f2f713f0a6c4d82acb64ed3aa831cee
      password: 7ac2c65487d34a7fa73997fada11d730

    object_storage:
      authUrl: 3837e5ff588b4470af5aa617a1766bde
      password: 378cb4362b044d07912724fabe675dac
      url: 6e67697af7ee4ca5963bd29e028e904b
      tenantId: b7d8458d714a40f8a229061e3dbf810f
      username: eb228aac947c4989be561ac95ee42c6b
      containerName: 4c3b4227ce904561ac012c685e35d1dd

    order_redis:
      host: 6a3cb866ffb043a7aa455f6a019e322d
      port: 5921efed8af14a18a4db38b48808431c
      password: b8ca506f6efe4248927c4aee64e6c695
      range: 2aa15df0aa2c434999f6498f0251e9f1

    cart_redis:
      host: 87e11d8fd3eb4f2a8bd6215c5507d3be
      port: 8665cb8cfad34d99a1d906b513bebc71
      password: 6b63e66844dc47f295e2012d18d5b8e9
      range: 87dd6ba543394f86961f59dc68704e5d

eureka:
  client:
    register-with-eureka: true  # Eureka에 서비스 등록
    fetch-registry: true  # Eureka에서 서비스 목록 가져오기
    service-url:
      defaultZone: http://eureka:8761/eureka  # Eureka 서버 URL

aladin:
  api:
    url: https://www.aladin.co.kr/ttb/api/ItemList.aspx?ttbkey=ttbfkqlaus1419001&Cover=Big&output=js&Version=20131101
    url2: https://www.aladin.co.kr/ttb/api/ItemLookUp.aspx?ttbkey=ttbfkqlaus1419001&Cover=Big&output=js&Version=20131101&OptResult=ebookList,usedList,reviewLis
## https://www.aladin.co.kr/ttb/api/ItemLookUp.aspx?ttbkey=ttbfkqlaus1419001&itemIdType=ISBN&ItemId=%s&OptResult=ebookList,usedList,reviewList";