server:
  port: 10143



springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  elasticsearch:
    uris: http://10.116.64.14:9200/
    username: elastic
    password: nhnacademy123!

  datasource:
    url: jdbc:mysql://10.116.64.14:13306/project_be8_plzbuybook_bookstore
    username: project_be8_plzbuybook
    password: "MOW6c#y4TVxi1P5b"
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 10.116.64.14
      port: 6379
      password: "*N2vya7H@muDTwdNMR!"
    jpa:
      properties:
        hibernate:
          show_sql: true
          format_sql: true
      hibernate:
        ddl-auto: none
      open-in-view: false # osiv 비활성화

  #    auth_redis_range: 231
#    order_redis_range: 232
#    cart_redis_range: 233
#    auth_code_redis_range: 234
#    database: 0

  application:
    name: bookstore

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: nhn



logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            core: DEBUG
      elasticsearch:
        client: DEBUG




#h2:
#    console:
#      enabled: true  # H2 콘솔 활성화
#      path: /h2-console  # H2 콘솔 접근 경로

eureka:
  client:
    register-with-eureka: true  # Eureka에 서비스 등록
    fetch-registry: true  # Eureka에서 서비스 목록 가져오기
    service-url:
      defaultZone: http://localhost:10149/eureka  # Eureka 서버 URL

aladin:
  api:
    url: https://www.aladin.co.kr/ttb/api/ItemList.aspx?ttbkey=ttbfkqlaus1419001&Cover=Big&output=js&Version=20131101
    url2: https://www.aladin.co.kr/ttb/api/ItemLookUp.aspx?ttbkey=ttbfkqlaus1419001&Cover=Big&output=js&Version=20131101&OptResult=ebookList,usedList,reviewLis

