### 회원 장바구니 조회
GET http://localhost:8090/api/bookstore/carts
Content-Type: application/json
X-USER-ID: cart@naver.com

### 회원 장바구니 단일 조회
GET http://localhost:8090/api/bookstore/carts/3
Content-Type: application/json
X-USER-ID: cart@naver.com

### 회원 장바구니 수정
PUT http://localhost:8090/api/bookstore/carts
Content-Type: application/json
X-USER-ID: cart@naver.com

{
  "cartBookId": 2,
  "sellingBookId": 259,
  "quantity": 1
}

### 회원 장바구니 등록
POST http://localhost:8090/api/bookstore/carts
Content-Type: application/json
X-USER-ID: cart@naver.com

{
  "sellingBookId": 265,
  "quantity": 1
}

### 회원 장바구니 삭제
DELETE http://localhost:8090/api/bookstore/carts
Content-Type: application/json
X-USER-ID: cart@naver.com

{
  "cartId": 1,
  "cartBookId": 2
}


### 회원 장바구니 전체 삭제
DELETE http://localhost:8090/api/bookstore/carts/1
Content-Type: application/json
X-USER-ID: cart@naver.com


