# curl -X POST http://localhost:8090/api/books/sync
POST http://localhost:8090/api/books/sync

###

POST http://localhost:8090/api/books/sync/isbn
Content-Type: application/json

["9781234567897", "9782345678901", "9783456789012"]


