### 프로젝트 실행시키면 무조건 한번 실행되는 http 요청 - 실행 버튼 안눌러도돼.
POST http://localhost:8090/api/book

### 기본호출
POST http://localhost:8090/api/books/sync

###asd
POST http://localhost:8090/api/books
Content-Type: application/json

{
  "bookTitle": "GD2 도서",
  "bookIndex": "GD2 목차",
  "bookDescription": "GD2 설명",
  "bookPubDate": "2024-01-01",
  "bookPriceStandard": "50000.00",
  "bookIsbn13": "130922",
  "publisherId": 75,
  "imageUrl": "https://i1.sndcdn.com/artworks-mCr382qpxrNfyfbc-tVzfKw-t500x500.jpg"
}


###  엘라스틱서치 조회
GET http://localhost:8090/api/books/search/305

### 엘라스틱 출판사 조회
GET http://localhost:8090/api/publishers/search/204

### 작가아이디로 작가가 쓴 책 조회
GET http://localhost:8090/api/books/search/test/413

### 카테고리
GET localhost:8090/api/categories?keyword=판타지

### 출판사
POST http://localhost:8090/api/publishers
Content-Type: application/json

{
  "publisherName": "출판사 1"

}

### 셀링북 삭제
DELETE localhost:8090/api/selling-books/272

### 작가로 검색 db
GET localhost:8090/api/books/authors/334

### 작가 저장
POST http://localhost:8090/api/authors
Content-Type: application/json

{
  "authorName": "리얼루다가3"

}

### asd

GET localhost:8090/api/books/434/selling-books

###작가 삭제
DELETE localhost:8090/api/authors/108

### 작가 이름으로 조회
GET http://localhost:8090/api/search/한강

### 이름 조회 인코딩
GET http://localhost:8090/api/search/%ED%85%8C%EC%8A%A4%ED%8A%B8%EC%9E%91%EA%B0%80


### 키워드 검색
GET localhost:8090/api/books?searchKeyword=한강


### 카테고리 검색
GET localhost:8090/api/categories/search?keyword=국내

### 페이징

GET http://localhost:8090/api/books?searchKeyword=한강&page=0


### asd

GET http://localhost:8090/api/books/test2



### 특정 조건으로 호출
# QueryType=Bestseller: 베스트셀러 조회
# SearchTarget=Foreign: 외국 도서만 검색
# start=1: 첫 번째 아이템부터 시작
# maxResults=20: 한 번에 20개씩 가져오기
POST http://localhost:8090/api/books/sync?queryType=Bestseller&searchTarget=Foreign&maxResults=50


### 신간 리스트 전체 조회 - 50개 나옴
POST http://localhost:8090/api/books/sync?queryType=ItemNewAll&searchTarget=Book&start=1&maxResults=50

### 블로거 베스트 셀러
POST http://localhost:8090/api/books/sync?queryType=BlogBest&searchTarget=Book&start=1&maxResults=50


### 베스트 셀러 외국 도서 - 60 개 나옴
POST http://localhost:8090/api/books/sync?queryType=Bestseller&searchTarget=Foreign&start=1&maxResults=20


### 베스트 셀러 국내도서 - 50개 나옴
POST http://localhost:8090/api/books/sync?queryType=Bestseller&searchTarget=Book&start=1&maxResults=10

### /sync/isbn는 여러 ISBN 리스트를 받아 한 번에 저장할 수 있습니다.
POST http://localhost:8090/api/books/sync/isbn
Content-Type: application/json

[
  "9791193852279"
]


### 9788936434267이라는 ISBN을 기반으로 알라딘 API를 호출하고, 도서 데이터를 저장합니다. (특정 isbn 으로 저장 가능) / 9788936434120 - 소년이 온다
POST http://localhost:8090/api/books/sync/itemid/9791193852279
s/sync

### ㅁㄴㅇㄴ

GET http://localhost:8080/api/books?searchKeyword=한강&page=0

###ㅁㄴㅇ
GET http://localhost:8080/api/books?searchKeyword=한강&searchAfter=321

###


### 카테고리 저장 테스트
POST localhost:8090/api/categories
Content-Type: application/json

{
    "parentCategoryId": 584,
    "parentCategoryName": "일본요리",
    "newCategoryName": "New Category3 일본데스까"
}

### 카테고리 저장 테스트
POST localhost:8090/api/categories
Content-Type: application/json

{

  "newCategoryName": "New root Category"
}


### /sync/isbn는 여러 ISBN 리스트를 받아 한 번에 저장할 수 있습니다.
POST http://localhost:8090/api/books/sync/isbn
Content-Type: application/json

[
  "9791158682934",
  "9788972558897"
]



### 9788936434267이라는 ISBN을 기반으로 알라딘 API를 호출하고, 도서 데이터를 저장합니다. (특정 isbn 으로 저장 가능) / 9788936434120 - 소년이 온다
POST http://localhost:8090/api/books/sync/itemid/9788972558897


### 태그 생성
POST localhost:8090/api/tags?bookId=1
Content-Type: application/json

{
  "tagName": "버러지태그4"
}



### 태그랑 북 연결
POST localhost:8090/api/book-tags?bookId=1&tagId=12

###
GET localhost:8090/api/book-tags?tagId=12

### 결아햄 이거야 이거

POST http://localhost:8090//api/admin/selling-books/register
Content-Type: application/json

{
  "bookTitle": "Test Book Title",
  "bookIndex": "12345",
  "bookDescription": "A description of the test book.",
  "bookPubDate": "2025-01-01",
  "bookPriceStandard": 25.99,
  "bookIsbn13": "1234567890123",
  "publisher": "창비",
  "imageUrl": "http://example.com/image.jpg",
  "categories": [
    { "categoryName": "국내도서",
      "categoryId": 1
    }
  ],
  "authors": ["John Doe", "Jane Smith"]
}


### ㄹㅈㄹ
GET localhost:8090/api/admin/selling-books