### 비회원 장바구니 조회
GET http://localhost:8090/api/bookstore/guests/carts
Content-Type: application/json

### 비회원 장바구니 수정
PUT http://localhost:8090/api/bookstore/guests/carts/5728520439127886568?quantity=3
Content-Type: application/json

### 비회원 장바구니 등록
POST http://localhost:8090/api/bookstore/guests/carts
Content-Type: application/json

{
  "sellingBookId": 20,
  "quantity": 1
}

### 비회원 장바구니 삭제
DELETE http://localhost:8090/api/bookstore/guests/carts/5728520439127886568
Content-Type: application/json


### 비회원 장바구니 전체 삭제
DELETE http://localhost:8090/api/bookstore/guests/carts
Content-Type: application/json


