### 권한 생성(관리자)
POST http://localhost:8090/api/auths
Content-Type: application/json

{
  "name": "ADMIN"
}


### 권한 생성(회원)
POST http://localhost:8090/api/auths
Content-Type: application/json

{
  "name": "USER"
}

### 권한 수정
PUT http://localhost:8090/api/auths/{auth_id}
Content-Type: application/json

{
  "name": "SUPER ADMIN"
}

### 권한 삭제
DELETE http://localhost:8090/api/auths/{auth_id}

### 모든 권한 조회
PUT http://localhost:8090/api/auths




### 회원 권한 설정
POST http://localhost:8090/api/members/auths
Content-Type: application/json

{
  "memberId": 1,
  "authId": 2
}


### 회원 권한 조회
GET http://localhost:8090/api/members/{member_id}/auths


### 회원 권한 수정
PUT http://localhost:8090/api/members/{member_id}/auths
Content-Type: application/json

{
  "authId": 3
}

### 회원 권한 삭제
DELETE http://localhost:8090/api/members/{member_id}/auths/{auth_id}
Content-Type: application/json
