### 권한 설정(관리자)
POST http://localhost:8090/api/members/auths
Content-Type: application/json

{
  "authId": 1,
  "name": "ADMIN"
}

### 권한 설정(회원)
POST http://localhost:8090/api/members/auths
Content-Type: application/json

{
  "authId": 2,
  "name": "USER"
}

### 회원 권한 설정
POST http://localhost:8090/api/members/auths
Content-Type: application/json

{
  "memberId": 1,
  "authId": 2
}

### 회원 권한 조회
GET http://localhost:8090/api/members/1/auths
Content-Type: application/json

{
  "memberId": 1
}

### 회원 권한 삭제
DELETE http://localhost:8090/api/members/1/auths
Content-Type: application/json

{
  "memberId": 1
}
