#http://localhost:8090/api/points/conditions


POST http://localhost:8090/api/points/conditions
Content-Type: application/json

{
  "pointConditionName": "SILVER",
  "conditionPoint": 100,
  "conditionPercentage": null,
  "status": true
}

